image:
  tag: 0.1.4

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
  hosts:
    - host: hangul.thefron.me
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: hangul-ipsum-cert
     hosts:
       - hangul.thefron.me

env:
  - name: RAILS_ENV
    value: production
