apiVersion: v1
kind: Secret
metadata:
  name: hangul-ipsum-secret
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "hangul-ipsum-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKeyBase := (get $secretData "secret-key-base") | default (randAlphaNum 32 | b64enc) }}
  secret-key-base: {{ $secretKeyBase | quote }}
